apiVersion: policy.mcm.ibm.com/v1alpha1
kind: Policy
metadata:
  name: policy-networkpolicy-gb
  namespace: default
  annotations:
    policy.mcm.ibm.com/standards: 
    policy.mcm.ibm.com/categories: 
    policy.mcm.ibm.com/controls: 
spec:
  complianceType: musthave
  remediationAction: enforce
  disabled: false
  namespaces:
    exclude: ["kube-*"]
    include: ["team2"]
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: policy-networkpolicy-gb
          namespace: team2
        spec:
          egress:
          - ports:
            - port: 6379
              protocol: TCP
            to:
            - namespaceSelector:
                matchLabels:
                  tier: frontend
            - podSelector:
                matchLabels:
                  tier: frontend
          ingress:
          - from:
            - namespaceSelector:
                matchLabels:
                  tier: frontend
            - podSelector:
                matchLabels:
                  tier: frontend
            ports:
            - port: 6379
              protocol: TCP
          podSelector:
            matchLabels:
              tier: backend
          policyTypes:
          - Ingress
          - Egress
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: binding-policy-networkpolicy-gb
  namespace: default
placementRef:
  name: placement-policy-networkpolicy-gb
  kind: PlacementPolicy
  apiGroup: mcm.ibm.com
subjects:
- name: policy-networkpolicy-gb
  kind: Policy
  apiGroup: policy.mcm.ibm.com
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: placement-policy-networkpolicy-gb
  namespace: default
spec:
  clusterLabels:
    matchExpressions:
      - {key: env, operator: In, values: ["prod"]}
